# Generated by Django 2.2.1 on 2019-05-25 09:07

import accounts.enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alcoholic',
            name='favorite_bearBrand',
        ),
        migrations.AlterField(
            model_name='alcoholic',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=accounts.enum.GenderEnum('Male'), max_length=15),
        ),
    ]
