# Generated by Django 2.2.1 on 2019-05-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bears', '0004_auto_20190525_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='bear',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bears', to='bears.ProfileUser'),
            preserve_default=False,
        ),
    ]
